### ISSUE TITLE
cannot stat 'application-x-executable': No such file or directory

### ISSUE THREAD

**Issue by raven2cz** [OliverLew/xdg-xmenu#1]
Hello,
I'm trying your "feeding" app for xmenu. But I've got error msg:

❯ ./xdg-xmenu > menu
cp: cannot stat 'application-x-executable': No such file or directory
fall back icon cannot be found

**Comment by xlucn** [comment]
Well, this script is not so rigorous now due to not strictly conforming to freedesktop standards and my lacking of coding ability :).

I pushed a new commit to omit the icon field if the script couldn't find any instead of exit directly, you can try it and see if it works.

However if there is indeed an icon named 'application-x-executable' on your system then it's probably another issue here, so would you check if that is the case by something like
```sh
$ find /usr/share/icons -name application-x-executable.*
```

**Comment by raven2cz** [comment]
Works thanks!
