### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by jzbor** [OliverLew/xdg-xmenu#5]
Hi,
As you haven't specified a license for this project, is it fine with you if I distribute a slightly modified version in my script collection under the BSD license?
Thanks for the great script btw!

**Comment by xlucn** [comment]
Ahh. I really don't know that much about software licenses, neither about how to choose one. I normally choose MIT license for my small single-script projects, since I think that one is quite permissive. Does that allow you to do what you want to do? If so I can add MIT license to my project, and also, it's absolutely fine with me!

If your modification is about improving this script and is suitable for most users, a PR is also welcome :)

**Comment by jzbor** [comment]
Thanks, yeah I am also new to the whole licensing thing. I am just currently collecting some nice scripts I find useful. They are from over the place and some of them are licensed. I don't want to step on anyones feet, so I figured I'd just ask. I ended up spending my afternoon on sorta-rewriting it in python because it brings a huge speed improvement. If you want to I can share or create a PR when I'm finished... Thanks for the great work and the quick response :D

**Comment by xlucn** [comment]
I also planned to rewrite in python or other languages, too. The reason is I found shell script is slow if I want to scan and generate the menu dynamically every time `xmenu` is spawned (basically like any other menu programs). But since you are completely rewriting it, I won't bother you for a PR then.

As for the license, I found a question to a similar situation:

https://opensource.stackexchange.com/questions/7673/can-i-take-mit-licensed-code-and-distribute-it-under-bsd

I guess I can add the MIT license, and you can simply mention this repo and the license. Now that you have rewritten in python I am actually not sure the license still requires the licence compatibility, but still, welcome to add the reference.

**Comment by jzbor** [comment]
If you are interested [here](https://github.com/jzbor/mashup/blob/master/utils/xdg-xmenu) you go. It always loads new desktop files, but not necessarily icons, as they cause the big latency. I cannot really say how buggy it is or isn't, cause I just finished, but it seems to work fine. I also added a little notice at the top of the source :D.

**Comment by xlucn** [comment]
I got busy since last reply that I forgot about this issue, sorry. The python script is awesome!

My idea about icon caching, when I was considering a python version before, was to try either multi-threading or background execution (then the user has to start again to see new icons). Not sure if that is a good way to do it.

Anyway, I think this issue can be closed.
